### ISSUE TITLE
Counter on a while

### ISSUE THREAD

**Issue by manuelgitgomes** [manuelgitgomes/TP1-PSR#1]
I see you had a problem with the while cycle @Sarxell. What you can do is do a while cycle without any conditions. After that, append the letter typed to a list. Place an if condition that counts the number of members of that list. If it's above the maximum value, break the cicle. Do you want me to implement this?

**Comment by Sarxell** [comment]
I think I understand what u are saying, I'm going to trade it and if it's still not the best way you can fix it!

**Comment by manuelgitgomes** [comment]
Issue solved, closing it
